version: '3.8'
services:
  # Database
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sae_frontoffice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./Docker/ScriptBD:/docker-entrypoint-initdb.d/:ro
      - ./db:/var/lib/mysql

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: containerPMA
    restart: always
    depends_on:
      - db
    ports:
        - '8081:80'
    environment:
        PMA_HOST: db

  # PHP
  php:
    container_name: php
    build:
      context: ./Docker/PHP
    ports:
      - '9000:9000'
    volumes:
        - ./src/sae5-jdc:/var/www/symfony_docker
    depends_on:
      - db

  # Application
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src/sae5-jdc:/var/www/symfony_docker
      - ./Docker/Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - php
      - db
