version: '1'

services:
    sae-php:
        build: .
        restart: unless-stopped
        ports:
            - "8000:8080"
            # HTTPS
            - target: 80
              published: ${HTTP_PORT:-80}
              protocol: tcp
            # HTTPS
            - target: 443
              published: ${HTTPS_PORT:-443}
              protocol: tcp
        volumes:
            - .:/app

    sae-mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        env_file: .env
        volumes:
          - SAE-db:/var/lib/mysql

volumes:
    SAE-db: